DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pinned boolean DEFAULT FALSE,
  title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  description VARCHAR(7000) NOT NULL,
  category_id INTEGER NOT NULL,
  initiator_id INTEGER NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE,
  lat FLOAT,
  lon FLOAT,
  paid boolean DEFAULT FALSE,
  confirmed_requests INTEGER,
  participant_limit INTEGER DEFAULT 0,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  published_on TIMESTAMP WITHOUT TIME ZONE,
  request_moderation boolean DEFAULT TRUE,
  state VARCHAR(32) NOT NULL,
  views BIGINT DEFAULT 0,
  CONSTRAINT fk_events_categories FOREIGN KEY (category_id) REFERENCES categories (id),
  CONSTRAINT fk_events_users FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(32) NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT fk_requests_events FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT fk_requests_users FOREIGN KEY (requester_id) REFERENCES users (id),
  CONSTRAINT uq_request UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
  compilation_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
  CONSTRAINT fk_compilation_events_compilations FOREIGN KEY (compilation_id) REFERENCES compilations (id),
  CONSTRAINT fk_compilation_events_events FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR(1000) NOT NULL,
  author_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  created_on TIMESTAMP WITHOUT TIME ZONE,
  updated_on TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT fk_comments_users FOREIGN KEY (author_id) REFERENCES users (id),
  CONSTRAINT fk_comments_events FOREIGN KEY (event_id) REFERENCES events (id)
);

